language: c
env:
  TOOL_VERSION=5.16.2
script: asdf plugin test perl https://github.com/ouest/asdf-perl.git --asdf-tool-version $TOOL_VERSION
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
